version: '3.3'
services:
  kaldi:
    image: "smartcommunitylab/kaldi-online-tcp:spanishmodel"
  web:
    image: "smartcommunitylab/kaldi-webrtc"
    volumes:
      - ./servers.json:/server/servers.json
    ports:
      - "8080:8080"